### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by peppy** [TimOliver/PhotoSorter#1]
I think this method is missing implementation:

https://github.com/TimOliver/PhotoSorter/blob/4c546376994e473776cc3d51ca4443459cf6e44e/PhotoSorter/main.swift#L56

**Comment by nekodex** [comment]
+1 can reproduce

**Comment by peppy** [comment]
Haven't heard anything back for almost one week – could we get an update on this issue? It is quite important to my workflow.

**Comment by peppy** [comment]
Looks to have since been resolved, closing.
